[deps]
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PlutoTeachingTools = "661c6b06-c737-4d37-b85c-46df65de6f69"
MarkdownLiteral = "736d6165-7244-6769-4267-6b50796e6954"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
